version: '3'

services:
  java-web-app:
    build: ./docker-project/project
    working_dir: /app/project
    volumes:
      - ./docker-project/project:/app/project
    expose:
      - "8084"
    ports:
      - "8082:8084"
    command: mvn clean spring-boot:run

  mysql-db:
    image: "alpine-mysql"